### ISSUE TITLE
result of askForPermission

### ISSUE THREAD

**Issue by piyushgoel997** [tajchert/Nammu#16]
The functions permissionGranted() and permissionRefused() aren't executed when the permission is granted or refused for the first time.
They will only execute after restarting the app. 
Is there any way to get them executed without restarting the app.

**Comment by tajchert** [comment]
I just tried on a sample app and both works fine.
Make sure to try it on MainActivity not on the MyFragment (not used for a sample).
If problem persist, please try to debug it and share some more in deep thoughts on this (scenario to recreate problem?).
