### ISSUE TITLE
SDK is out!

### ISSUE THREAD

**Issue by quentin23soleil** [tajchert/Nammu#4]
Hey, now that the sdk is out, could you release it on jcenter?

Cheers,

**Comment by tajchert** [comment]
Thanks for reminder :) I will upload it but firstly I need to add more useful feature, ETA is 1-2 weeks.

**Comment by quentin23soleil** [comment]
cool ;)

**Comment by tajchert** [comment]
I updated Nammu with easier monitoring, coverage of all permissions, better/easier sample, ignored lists of permissions.

I will wait some time to test those features before rolling into jcenter to be sure it is stable.

**Comment by k0shk0sh** [comment]
i see that you released version 1.0.0 but gradle can't find it  or the other old one 0.4.5 `maven { url "https://jitpack.io" }`

**Comment by tajchert** [comment]
@k0shk0sh take a look here: https://github.com/tajchert/RuntimePermissionWorkshop
I used there 1.0.0 version and it works.

In this commirt you can find how to add jitpack library: https://github.com/tajchert/RuntimePermissionWorkshop/commit/eacbcbf492a27bbc8dadb74a38388155f85422c3
