### ISSUE TITLE
sdk:minSdkVersion 

### ISSUE THREAD

**Issue by ghost** [tajchert/Nammu#7]
Error:Execution failed for task ':processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.github.tajchert:nammu:1.0.0] 

Can this library have minSdkVersion be 14 or lower?

**Comment by FabianTerhorst** [comment]
Have you tried to add `<uses-sdk tools:overrideLibrary="pl.tajchert.nammu"/>`
 in your manifest?

**Comment by IliaEremin** [comment]
@FabianTerhorst the question is does it affect on library work?

**Comment by tajchert** [comment]
@mingqlin  - lowered it to 14 as requested.
